# Generated by Django 5.1.3 on 2025-01-02 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_review_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.country'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='payment_icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/payment_icons/'),
        ),
    ]
