# Generated by Django 5.1.3 on 2025-01-02 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_paymenttype_country_paymenttype_payment_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.currency'),
        ),
    ]
