# Generated by Django 5.1.3 on 2025-01-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_paymenttype_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='country',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
