# Generated by Django 5.1.3 on 2025-01-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_paymenttype_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('ipn_secret', models.CharField(max_length=255)),
            ],
        ),
    ]
