# Generated by Django 5.1.3 on 2025-01-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_paymentconfigurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfigurations',
            name='gateway',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
