# Generated by Django 5.1.3 on 2025-01-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_paymentconfigurations_gateway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='payment_icon',
            new_name='icon',
        ),
    ]
