# Generated by Django 5.1.3 on 2024-12-04 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_currency_review_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.currency'),
        ),
    ]
