services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=survey_db
      - POSTGRES_USER=anexx
      - POSTGRES_PASSWORD=Jobweb@2019
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anexx -d survey_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind unix:/app/app.sock"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - socket_volume:/app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONUNBUFFERED=1
      - DJANGO_SUPERUSER_EMAIL=anexx61@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=Jobweb@2019
    env_file:
      - .env

  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx/restore.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
      - socket_volume:/app
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl:/etc/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  socket_volume:
  postgres_data:
