# Generated by Django 5.1.3 on 2024-12-03 00:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_review_user_review_currency_review_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Currency',
            new_name='currency',
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
