# Generated by Django 5.1.7 on 2025-04-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_referralearning_referreduser_referralactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('threshold', models.PositiveIntegerField()),
                ('icon', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('text_color', models.CharField(max_length=50)),
                ('border_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLevelBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='users.referrallevel')),
            ],
        ),
    ]
