# Generated by Django 5.1.7 on 2025-04-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_referrallevel_referrallevelbenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='surveys_completed',
            field=models.IntegerField(default=0),
        ),
    ]
